### ISSUE TITLE
Outdated jQuery dependency in bower.json?

### ISSUE THREAD

**Issue by wmayner** [Hypercubed/angular-downloadsvg-directive#2]
When I try to `bower install angular-downloadsvg-directive`, I'm getting a `bower ECONFLICT Unable to find suitable version for jquery`. Can the `bower.json` be changed to require `"jquery": ">= 1.11.0"` instead of `"jquery": "~1.11.0"`, or does it really need something close to that version?

Thanks for this awesome little directive!

**Comment by Hypercubed** [comment]
jquery is only required because the jqLite's `.css` function only retrieves inline-styles.  I see no reason why it would not work with future versions but I haven't tested it.  Ideally I should take the time to write my own `copyCSS` function using `getComputedStyle` and avoid the jquery requirement altogether.

**Comment by Hypercubed** [comment]
I finally removed the jQuery dependency all together.  Thanks!
